name: check
on:
  push:

jobs:
  vcpkg:
    name: Check vcpkg
    runs-on: windows-2022
    strategy:
      matrix:
        arch:
          x64
    env:
      VCPKG_ROOT: C:\vcpkg
      VCPKG_VERSION: ${{ github.workspace }}/vcpkg_version
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache
      VCPKG_TARGET_TRIPLET: ${{ matrix.arch }}-windows-static

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Get vcpkg version
      uses: actions/cache@v2
      with:
        path: ${{ env.VCPKG_VERSION }}
        key: any
    - name: "Create cache directory"
      id: prepare
      run: |
        mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
        cd ${{ env.VCPKG_ROOT }}
        Get-ChildItem -Recurse
        if (${{ steps.prepare.outputs.cache-hit }}) {
          $env:HEAD = Get-Content ${{ env.VCPKG_VERSION }}
          git checkout $env:HEAD
        }
        $env:HEAD = $(git rev-parse --short HEAD)
        Set-Content ${{ env.VCPKG_VERSION }} $env:HEAD
        echo "::set-output name=head::$env:HEAD"
      shell: bash
    - name: Restore vcpkg and its artifacts.
      uses: actions/cache@v2
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: |
          ${{ hashFiles( '.github/workflows/build.yaml' ) }}-${{ steps.prepare.outputs.head }}-${{ matrix.arch }}
    - name: Installing dependencies
      run: |
        choco install innosetup
        vcpkg install --disable-metrics --triplet=${{ env.VCPKG_TARGET_TRIPLET }} asio gettext libpng icu glbinding sdl2 sdl2-ttf sdl2-mixer[libvorbis,libflac,mpg123] sdl2-image[libjpeg-turbo,tiff] graphite2 harfbuzz opusfile libwebp
