name: Build
on:
  push:
    branches: [ master ]

jobs:
  vcpkg:
    env:
      VCPKG_ROOT: C:\vcpkg
      VCPGK_COMMIT: 7bb175eafedb203f19b18cf211666ec728c7461a
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache
      VCPKG_TARGET_TRIPLET: ${{ matrix.arch }}-windows-static

    steps:
    - name: "Create cache directory"
      run: mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
      shell: bash
    - name: Installing dependencies
      run: |
        pushd ${{ env.VCPKG_ROOT }}
        ls -la
        git checkout ${{ env.VCPGK_COMMIT }} || true
        git status || true
        popd
        vcpkg install --disable-metrics --triplet=${{ env.VCPKG_TARGET_TRIPLET }} sdl2-mixer[libvorbis,libflac,mpg123]

