name: Build
on:
  push:
    branches: [ master ]

jobs:
  vcpkg:
    name: Check vcpkg
    runs-on: windows-latest
    env:
      VCPKG_ROOT: C:\vcpkg
      VCPKG_TARGET_TRIPLET: x64-windows-static
      VCPKG_COMMIT: 7bb175eafedb203f19b18cf211666ec728c7461a

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check version
      run: |
        $env:LAST = perl -n -e'/VCPKG_COMMIT: ([0-9a-z]+)/ and print($1)' .github/workflows/build.yaml
        cd ${{ env.VCPKG_ROOT }}
        $env:HEAD = git rev-parse HEAD
        if ("$env:LAST" -Match "$env:HEAD") {
          echo "No update availabe"
          exit 0
        }
        echo "VCPKG updated from $env:LAST to $env:HEAD"
    - name: Update version
      run: |
        $env:DATE = Get-Date -Format "ddMMyyyy"
        $env:BRANCH = vcpkg-update-$env:DATE
        git checkout -b $env:BRANCH
        perl -p -i -e's/(VCPKG_COMMIT:) [0-9a-z]+/$1 $env:HEAD/' .github/workflows/build.yaml
        git config --global user.name "bunnybot"
        git config --global user.email "bunnybot@widelands.org"
        git add .github/workflows/build.yaml
        git commit -m "Update vcpkg"
        git push --set-upstream origin $env:BRANCH
