name: Build
on:
  push:
    branches: [ master ]

jobs:
  vcpkg-packages:
    strategy:
      matrix:
        arch: [x64, x86]
    name: Build vcpkg packages for ${{ matrix.arch }}
    runs-on: windows-2022
    env:
      VCPKG_ROOT: C:\vcpkg
      VCPKG_TARGET_TRIPLET: ${{ matrix.arch }}-windows-static
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Get vcpkg version
      id: prepare
      run: |
        pushd ${{ env.VCPKG_ROOT }}
        HEAD=$(git rev-parse --short HEAD)
        popd
        echo -n $HEAD > .github/scripts/vcpkg_ref
        git config --global user.name "The Widelands Build Bot"
        git config --global user.email "bunnybot@widelands.org"
      shell: bash
    - name: Check whether cache exists
      id: lookup
      uses: actions/cache@v3
      with:
        path: ${{ env.VCPKG_ROOT }}/installed
        key: |
          ${{ hashFiles( './install-dependencies.sh', '.github/scripts/vcpkg_ref' ) }}-${{ matrix.arch }}
    - name: Building packages
      id: build
      if: steps.prepare.lookup.cache-hit != 'true'
      run: ./install-dependencies.sh vcpkg --triplet=${{ env.VCPKG_TARGET_TRIPLET }}
      shell: bash
    - name: Update vcpkg_ref
      if: ${{ success() && steps.prepare.lookup.cache-hit != 'true' }}
      run: |
        git add .github/scripts/vcpkg_ref
        git commit -m "Update vcpkg version"
        # git push "https://bunnybot:${{ secrets.WIDELANDS_FORMAT_TOKEN }}@github.com/${{ github.action_repository }}.git" master
        git push "https://matthiakl:${{ secrets.ACTION_TOKEN }}@github.com/${{ github.action_repository }}.git" master
      shell: bash
