name: Build
on:
  push:
    branches: [ master ]

jobs:
  vcpkg:
    name: Check vcpkg
    runs-on: windows-latest
    env:
      VCPKG_ROOT: C:\vcpkg
      VCPKG_TARGET_TRIPLET: x64-windows-static

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check version
      run: |
        $env:LAST = Get-Content vcpkg_version
        cd ${{ env.VCPKG_ROOT }}
        $env:HEAD = git rev-parse HEAD
        if ("$env:LAST" -Match "$env:HEAD") {
          echo "No update availabe"
          exit 0
        }
        echo "VCPKG updated from $env:LAST to $env:HEAD"
    - name: Update version
      run: |
        $env:DATE = Get-Date -Format "ddMMyyyy"
        $env:BRANCH = "vcpkg-update-$env:DATE"
        git checkout -b $env:BRANCH
        echo $env:HEAD > vcpkg_version
        git config --global user.name "bunnybot"
        git config --global user.email "bunnybot@widelands.org"
        git add vcpkg_version
        git commit -m "Update vcpkg"
        git push --set-upstream origin $env:BRANCH
