name: Build
on:
  push:
    branches: [ master ]

jobs:
  vcpkg:
    name: Check vcpkg
    runs-on: windows-latest
    env:
      VCPKG_ROOT: C:\vcpkg
      VCPKG_VERSION: ${{ github.workspace }}/vcpkg_version

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check version
      run: |
        cd ${{ env.VCPKG_ROOT }}
        $env:LAST = Get-Content ${{ env.VCPKG_VERSION }}
        $env:HEAD = git rev-parse HEAD
        if ("$env:LAST" -Match "$env:HEAD") {
          echo "No update availabe"
          exit 0
        }
        echo "VCPKG updated from $env:LAST to $env:HEAD"
    - name: Update version
      run: |
        $env:DATE = Get-Date -Format "ddMMyyyy"
        $env:BRANCH = "vcpkg-update-$env:DATE"
        Set-Content ${{ env.VCPKG_VERSION }} $env:HEAD
        git config --global user.name "bunnybot"
        git config --global user.email "bunnybot@widelands.org"
        git add ${{ env.VCPKG_VERSION }}
        git commit -m "Update vcpkg"
        git push --set-upstream origin $env:BRANCH
    - name: Create pull request for $env:BRANCH
      id: create-pr
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let response = await github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "Update vcpkg version",
            head: "$env:BRANCH",
            base: "master",
            body: `Update VCPKG from $env:LAST to $env:HEAD`
          });
          return response.data.number
