name: Build
on:
  push:
    branches: [ master ]

jobs:
  vcpkg-packages:
    strategy:
      matrix:
        arch: [x64, x86]
    name: Build vcpkg packages for ${{ matrix.arch }}
    runs-on: windows-2022
    env:
      VCPKG_ROOT: C:\vcpkg
      VCPKG_TARGET_TRIPLET: ${{ matrix.arch }}-windows-static
    outputs:
      result-x64: ${{ steps.build.outputs.result-x64 }}
      result-x86: ${{ steps.build.outputs.result-x86 }}
      vcpkg_ref: ${{ steps.prepare.outputs.vcpkg_ref }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Get vcpkg version
      id: prepare
      run: |
        pushd ${{ env.VCPKG_ROOT }}
        HEAD=$(git rev-parse --short HEAD)
        popd
        echo "Current HEAD is $HEAD"
        echo "vcpkg_key=${{ hashFiles( './install-dependencies.sh' ) }}-${HEAD}" >> $GITHUB_OUTPUT
        # Test newest toolset
        toolset=$(curl https://raw.githubusercontent.com/actions/runner-images/main/images/win/toolsets/toolset-2022.json | \
                  jq '.visualStudio.workloads[] | capture("Component\\.VC\\.(?<v>[0-9]+\\.[0-9]+)(\\.[0-9]+){2}\\.x86\\.x64") | .v' | \
                  sort -u | tail -n 1 | tr -d '"')
        echo "Current toolset is ${toolset}"
        echo "toolset=${toolset}" >> $GITHUB_OUTPUT
        echo "vcpkg_ref=\"$HEAD ${toolset}\"" >> $GITHUB_OUTPUT
      shell: bash
    - name: Check whether cache exists
      id: lookup
      uses: actions/cache@v3
      with:
        # Explicit path here because env is overridden by msvc-dev-cmd
        path: C:\vcpkg\installed
        key: |
          ${{ steps.prepare.outputs.vcpkg_key }}-${{ matrix.arch }}
    - name: Building packages
      id: build
      if: steps.lookup.outputs.cache-hit != 'true'
      run: |
        ./install-dependencies.sh vcpkg --triplet=${{ env.VCPKG_TARGET_TRIPLET }}
        echo "result-${{ matrix.arch }}=true" >> $GITHUB_OUTPUT
      shell: bash
  update:
    needs: vcpkg-packages
    #if: ${{ needs.vcpkg-packages.outputs.result-x64 && needs.vcpkg-packages.outputs.result-x86 }}
    name: Commit new version
    runs-on: ubuntu-latest
    env:
      VCPKG_ROOT: C:\vcpkg
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Update vcpkg_ref
      run: |
        echo "Updating to ${{ needs.vcpkg-packages.outputs.vcpkg_ref }}"
        echo "${{ needs.vcpkg-packages.outputs.vcpkg_ref }}" > .github/scripts/vcpkg_ref
        if [ -n "$(git status -s)" ]; then
          git config --global user.name "The Widelands Build Bot"
          git config --global user.email "bunnybot@widelands.org"
          git add .github/scripts/vcpkg_ref
          git commit -m "Update vcpkg version"
          git push "https://matthiakl:${{ secrets.ACTION_TOKEN }}@github.com/${{ github.repository }}.git" master
        fi
      shell: bash
