name: Build
on:
  push:
    branches: [ master ]

jobs:
  vcpkg:
    name: Check vcpkg
    runs-on: windows-latest
    env:
      VCPKG_ROOT: C:\vcpkg
      VCPKG_TARGET_TRIPLET: x64-windows-static
      VCPGK_COMMIT: 7bb175eafedb203f19b18cf211666ec728c7461a

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check version
      run: |
        cd ${{ env.VCPKG_ROOT }}
        $env:HEAD = git rev-parse HEAD
        $env:LAST = perl -n -e'/VCPKG_COMMIT: ([0-9a-z]+)/ and print($1)' .github/workflows/build.yaml
        echo $env:LAST
        if ("$env:LAST" -Match "$env:HEAD") {
          echo "No update availabe"
          exit 0
        }
        git fetch
        git checkout ${{ env.VCPKG_COMMIT }}
        git status
    - name: Check dependencies
      run: |
        vcpkg install --disable-metrics --triplet=${{ env.VCPKG_TARGET_TRIPLET }} sdl2-mixer[libvorbis,libflac,mpg123]
    - name: Update version
      run: |
        git checkout -B vcpkg-update
        perl -p -i -e's/(VCPKG_COMMIT:) [0-9a-z]+/$1 $env:HEAD/' .github/workflows/build.yaml
        git add .github/workflows/build.yaml
        git commit -m "Update vcpkg"
        git push
