name: compile
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  vcpkg:
    name: vcpkg packages
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg-bincache
      VCPKG_TARGET_TRIPLET: x64-windows-static

    steps:
    - name: Build packages
      id: build
      run: |
        mkdir ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        vcpkg install --disable-metrics --triplet=${{ env.VCPKG_TARGET_TRIPLET }} boost gettext libpng icu glbinding sdl2 sdl2-ttf sdl2-mixer[libvorbis,libflac,mpg123] sdl2-image[libjpeg-turbo,tiff] graphite2 harfbuzz opusfile libwebp
