name: Cache
on:
  workflow_dispatch:

jobs:
  windows-msvc:
    # inspired by https://github.com/lukka/CppCMakeVcpkgTemplate/blob/main/.github/workflows/hosted-pure-workflow.yml
    needs: [clang_tidy, documentation, codecheck, misc_sanity_checks, lua_style]
    strategy:
      matrix:
        config: [Debug, Release]
        arch: [x64, x86]
    name: Windows ${{ matrix.config }} ${{ matrix.arch }} Build (MSVC)
    runs-on: windows-2022
    env:
      VCPKG_ROOT: C:\vcpkg
      VCPKG_TARGET_TRIPLET: ${{ matrix.arch }}-windows-static

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Checkout vcpkg
      id: prepare
      run: |
        read REF TOOLSET < .github/scripts/vcpkg_ref
        cd ${{ env.VCPKG_ROOT }}
        # REF can be empty, a commit hash or a pull request
        [ -n "$REF" ] && git fetch
        git checkout $REF || git pull origin $REF
        echo "vcpkg_key=${{ hashFiles( './install-dependencies.sh' ) }}-${REF}" >> $GITHUB_OUTPUT
        echo "toolset=${TOOLSET}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Restore vcpkg and its artifacts.
      uses: actions/cache@v3
      with:
        path: ${{ env.VCPKG_ROOT }}/installed
        key: |
          ${{ steps.prepare.outputs.vcpkg_key }}-${{ matrix.arch }}
    - name: Installing dependencies
      run: |
        ./install-dependencies.sh vcpkg --triplet=${{ env.VCPKG_TARGET_TRIPLET }}
      shell: bash